<?php
//APP AUTH DATA SECTION
const USER_ACCESS_TOKEN = 'CAAMPezIsKioBAH3I8oZClKvCOGTWG3oMVAwL2nL4HaaZBRgrjWPqze32L99GxVs4zTxeSHCLsOs0ZBAwcZAqkLvWrWSrOxMCY68b1znXywLnKGrav3C1vXGsmTHRF01hiPqoX6NoobRhAiwM3dGkiWSc53ppQKlAZCrnDPrp1wmy1kbWZAfqvpZAhi1Pyasib0pmGSOAaIfkqelNu07lJZAg';

const APP_ID = '861446727281194';
const APP_SECRET = '6b7a6ece1acc483e4a9338df1459b609';
const APP_ACCESS_TOKEN = '861446727281194|w_pjRNsl_SgKyPRcoypiKSgbqmQ';
const GENERATED_VERIFY_TOKEN = 'Sfdb1v50WDZw1lVDruQlG8eSNelqF8I0CQd6DIKSsk0MGP2xX9Nkzq7LXLmw1VSX';
const PAGE_ID = '812343388879186';
const PAGE_VERIFY_TOKEN = 'CAAMPezIsKioBAKMwvYkmv3OHlSR7sDGYFUszaDoNeU2uJF03dzXivcuaf0lehmfyDaf8IGurZCFVM971FYlT9xG67Ty7aZC9iv8TNKvwh3HaFXFyjACNOYiECVLtqOdAb7ZBkZAySygN2fHkA02NUmOwbeZA57CVrjkCKQ1SmrXF66KqR2XxmQfcKNrm7cZBcZD';
const APP_CALLBACK_URL = 'http://strelec.tomsk.ru/callback.php';
//ENDOF APP AUTH DATA SECTION

//APP SETTINGS SECTION
const CONVERSATION_AUTO_REPLY_MSG = 'It is a test conv reply';
const CONVERSATION_AUTO_REPLY_COOLDOWN = 3600;
const CONVERSATION_REPLY_ON = true;

const USER_POST_AUTO_REPLY_MSG = 'It is a test post reply';
const USER_POST_AUTO_REPLY_ON = true;
const USER_POST_AUTO_LIKE_ON = true;

const USER_COMMENT_AUTO_REPLY_MSG = 'It is a test comment reply';
const USER_COMMENT_AUTO_REPLY_ON = true;
const USER_COMMENT_AUTO_LIKE_ON = true;

const LOGGING_ON = true;
//ENDOF APP SETTINGS SECTION
